name: ${PROJECT}-project

services:
    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        container_name: ${PROJECT}_php
        build: 
          context: .docker/php
          args:
            USER_ID: ${USER_ID}
            GROUP_ID: ${GROUP_ID}
        ports:
            - 5173:5173
        volumes:
            - ./laravel:/var/www/html
        networks:
            - mynetwork

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        container_name: "${PROJECT}_nginx"
        hostname: ${PROJECT}.loc
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./laravel:/var/www/html
            - .docker/ssl:/etc/ssl/private
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
        networks:
            - mynetwork

    ####################################################################################################
    # DATABASE - Csak az egyik legyen kikommentelve!
    ####################################################################################################

    # MySQL
    mysql:
        container_name: "${PROJECT}_mysql"
        image: mysql:latest
        ports:
            - 3306:3306
        volumes:
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: carservice
            MYSQL_USER: user
            MYSQL_PASSWORD: .sweetpwd.
        networks:
            - mynetwork

    ####################################################################################################
    # phpMyAdmin
    ####################################################################################################
    phpmyadmin:
        container_name: "${PROJECT}_phpmyadmin"
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysql  # mariadb / mysql
            PMA_PORT: 3306
            UPLOAD_LIMIT: 256M
        networks:
            - mynetwork

networks:
  mynetwork:
    driver: bridge
